% config.m Configuration file for runExperiment 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Classifier configurations

% Example Classifier
exampleClassifierConfig = @ExampleClassifier;

% Random Forest - Parameters: numTrees
randomForest20Config = @() RandomForest(20);
randomForest100Config = @() RandomForest(100);

% Rotation Forest - Parameters: numTrees, splitParameter
rotationForest20Config = @() RotationForest(1,20);
rotationForest100Config = @() RotationForest(100,2);

% SVM - Parameters: KernelFunction, PolynomialOrder, Coding
svmLinearConfig = @() SVM(...
    'KernelFunction', 'linear', ...
    'Coding', 'onevsone');
svmPolynomial1vs1Config = @() SVM(...
    'KernelFunction', 'polynomial', ...
    'PolynomialOrder', 2, ...
    'Coding', 'onevsone');
svmPolynomial1vsAllConfig = @() SVM(...
    'KernelFunction', 'polynomial', ...
    'PolynomialOrder', 2, ...
    'Coding', 'onevsone');
svmLibLinearConfig = @() SVMlibsvm(...
    'KernelFunction', 'linear', ...
    'Coding', 'onevsone');
svmLightLinearConfig = @() SVMsvmlight(...
    'KernelFunction', 'linear', ...
    'Coding', 'onevsone');

% TSVM - Parameters: KernelFunction, PolynomialOrder, Coding
tsvmLinearConfig = @() TSVM(...
    'KernelFunction', 'linear', ...
    'Coding', 'onevsone');

% Convolutional Network - Parameters: cudnn, gpus, numEpochs
convNetConfig = @() ConvNet(...
    'cudnn', true, ...
    'gpus', [1], ...
    'numEpochs', 500, ...
    'plotErrorRates', true, ...
    'stoppingEpochWindow', 10, ...
    'stoppingErrorMargin', 0.005, ...
    'dropoutRate', 0.0, ...
    'doPooling', false);

% BasicEnsemble - Parameters: baseClassifiers, numClassifiers, 
%                             trainingInstanceProportions
basicEnsembleEC100_08Config = ...
    @() BasicEnsemble({ExampleClassifier}, ...
        100, ...
        0.8, ...
        VotingMode.WeightedMajority, ...
        0.1, ...
        true, ...
        true, ...
        true);
basicEnsembleLinearSVM100_001Config = ...
    @() BasicEnsemble({svmLinearConfig()}, ...
        100, ...
        0.002, ...
        VotingMode.WeightedMajority, ...
        0.5, ...
        true, ...
        true, ...
        true);
basicEnsembleRF20Config = ...
    @() BasicEnsemble({randomForest20Config()}, ...
        10, ...
        0.5, ...
        VotingMode.WeightedMajority, ...
        0.1, ...
        true, ...
        true, ...
        true);

% VisualizingClassifier
visualizingClassifierConfig = @() VisualizingClassifier();

% SpatialReg - Parameters: Classifier, R, [PropagationThreshold,]
%                          VisualizeSteps
randomForestLabelPropConfig = @() LabelPropagator(...
    randomForest20Config(), ...
    'R', 5, ...
    'PropagationThreshold', 0.0, ...
    'VisualizeSteps', true);
randomForestOutputRegConfig = @() OutputRegularizer(...
    ['../results/RandomForest_20/MulticlassLda_14/' ...
     'SpatialFeatureExtractor_5_Max_Mean_Min_Var/20170217_1012/'], ...
    'R', 5, ...
    'VisualizeSteps', false);


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Feature extractor configurations

% SELD - Parameters: k, numDimensions
seld20_5Config = @() SELD(20, 5);
seld20_14Config = @() SELD(20, 14);

% PCA - Parameters: numDimensions
pca5Config = @() PCA(5);
pca14Config = @() PCA(14);

% MulticlassLda
mcldaConfig_5 = @() MulticlassLda(5);
mcldaConfig_14 = @() MulticlassLda(14);

% ContinuumRemoval - Parameters: useMultithread
continuumRemoval= @() ContinuumRemoval(true);

% SpatialFeatureExtractor - Parameters: radius, implementationType
spatialFeatureExtractorConfig_5= @() SpatialFeatureExtractor(5, 1);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Experiment configurations



SAMPLE_SET_PATH = ...
        ['../data/ftp-iff2.iff.fraunhofer.de/FeatureExtraction/' ...
            'Samplesets/sampleset_012.mat'];


        
global NUMCLASSES;
NUMCLASSES = 24;

CLASSIFIER = convNetConfig();

EXTRACTORS = {mcldaConfig_14(), spatialFeatureExtractorConfig_5()};
EXTRACTORS = cellfun(@(x) NoFeatureExtraction(x), ...
                     EXTRACTORS, ...
                     'uniformoutput', false);
EXTRACTORS_PATHs = ...
    cellfun(@(x) x.toShortString(), EXTRACTORS, 'uniformoutput', false);
        
DATA_SET_PATH = ...
        '../data/ftp-iff2.iff.fraunhofer.de/ProcessedData/400-1000/';
DATA_SET_PATH = [fullfile(DATA_SET_PATH, EXTRACTORS_PATHs{:}) '/'];

RESULTS_PATH = '../results/';

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Output configurations

% log levels:
% ALL   = 0
% TRACE = 1
% DEBUG = 2
% INFO  = 3
% WARN  = 4
% ERROR = 5
% FATAL = 6
% OFF   = 7
LOG_LEVEL = 3;

VISUALIZE_TRAIN_LABELS = false;
VISUALIZE_TEST_LABELS = false;
VISUALIZE_PREDICTED_LABELS = true;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
