% config.m Configuration file for runExperiment 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Classifier configurations

exampleClassifierConfig = @ExampleClassifier;

svmLinearConfig = @() SVM(...
    'KernelFunction', 'linear', ...
    'Coding', 'onevsone');
svmPolynomialConfig = @() SVM(...
    'KernelFunction', 'polynomial', ...
    'Coding', 'onevsone');

tsvmLinearConfig = @() TSVM(...
    'C1', 10, ...
    'C1', 10, ...
    'KernelFunction', 'linear', ...
    'Coding', 'onevsone');
tsvmPolynomialConfig = @() TSVM(...
    'C1', 10, ...
    'C1', 10, ...
    'KernelFunction', 'polynomial', ...
    'Coding', 'onevsone');

svmLinearSpatiallyRegularizedConfig = @() SpatialReg(...
    svmLinearConfig(), ...
    5, ...
    true, ...
    true);
tsvmLinearSpatiallyRegularizedConfig = @() SpatialReg(...
    tsvmLinearConfig(), ...
    5, ...
    true, ...
    true);

basicEnsembleEC100_08Config = ...
    @()  BasicEnsemble({ExampleClassifier}, ...
        [100], ...
        [0.8]);
basicEnsembleSVM100_08Config = ...
    @()  BasicEnsemble({svmLinearConfig()}, ...
        [100], ...
        [0.1]);


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Feature extractor configurations

seld85Config = @() SELD(8, 5);

pca5Config = @() PCA(5);

mcldaConfig = @() MulticlassLda;

continuumRemoval= @() ContinuumRemoval;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Experiment configurations

classifier = ExampleClassifier()

extractors = {mcldaConfig()}

dataSetPath = ...
        '../data/ftp-iff2.iff.fraunhofer.de/Data/Hyperspectral/400-1000/'
sampleSetPath = ...
  '../data/ftp-iff2.iff.fraunhofer.de/Data/FeatureExtraction/sampleSet.mat'

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%